services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: talknest
      POSTGRES_PASSWORD: talknest
      POSTGRES_DB: talknest
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
