export const GenericErrors = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  CLIENT_ERROR: 'CLIENT_ERROR',
} as const;

export const UserErrors = {
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
  EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_USER_ID: 'INVALID_USER_ID',
  MISSING_USER_ID: 'MISSING_USER_ID',
} as const;